global using AutoMapper;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using Moq;
global using SquareFindings.Controllers;
global using SquareFindings.Entities;
global using SquareFindings.Models;
global using SquareFindings.Services;
global using Xunit;
